language: elm

sudo: required

node_js:
  - '8'

install:
  - npm i elm-coverage -g
  - npm i elm-test -g
  - npm i create-elm-app -g
  #- sudo ln -s /usr/lib/node_modules/elm-coverage/bin /usr/lib/node_modules/elm-coverage/unpacked_bin

script: 
  # - elm-test --verbose
  - elm-coverage
  # - npm run coveralls
