language: elm

sudo: required

node_js:
  - '8'

install:
  - npm i create-elm-app -g
  - npm i elm-coverage -g

script: 
  # - elm-test --verbose
  - elm-coverage --elm-test ./node_modules/.bin/elm-test
  # - npm run coveralls
